"""All ORM models.

Importing this package registers every table on ``Base.metadata``. Alembic's ``env.py`` and the
test fixtures both rely on that, so new model modules must be imported here.
"""

from app.models.ai import AIGenerationBatch, AIInteraction
from app.models.base import Base, TimestampMixin, utcnow
from app.models.cms import (
    Announcement,
    ContentCategory,
    ContentRevision,
    CourseCategory,
    FaqItem,
    MediaAsset,
    ProductCategory,
    SiteSection,
    SiteSetting,
)
from app.models.commerce import Order, OrderItem, Payment, Subscription
from app.models.content import Lesson, Resource, Video
from app.models.curriculum import (
    Course,
    Skill,
    SkillPrerequisite,
    SkillRelation,
    Subject,
    Topic,
    Unit,
)
from app.models.enums import (
    AssignmentStatus,
    AttendanceStatus,
    CategoryKind,
    DeliveryMode,
    EnrollmentStatus,
    LeadStatus,
    LearningFormat,
    MediaKind,
    NotificationKind,
    OrderStatus,
    PaymentStatus,
    QuestionType,
    ReviewStatus,
    SessionStatus,
    UserRole,
)
from app.models.ops import (
    AuditLog,
    LeadNote,
    Notification,
    TeacherCredential,
    TeacherSubjectAssignment,
)
from app.models.progress import (
    Achievement,
    Attempt,
    Certificate,
    CourseEnrollment,
    LessonProgress,
    PracticeSession,
    StudentAchievement,
    StudentSkillMastery,
    XPEvent,
)
from app.models.question import Question, QuestionVariant
from app.models.site import BlogPost, ContactLead, Testimonial
from app.models.tutoring import (
    Assignment,
    AssignmentSubmission,
    Attendance,
    ClassEnrollment,
    ClassGroup,
    LiveSession,
    ScheduleSlot,
    TutoringProduct,
    TutoringRequest,
)
from app.models.user import (
    ParentProfile,
    ParentStudentLink,
    StudentProfile,
    TeacherProfile,
    User,
)

__all__ = [
    "AIGenerationBatch",
    "AIInteraction",
    "Achievement",
    "Announcement",
    "Assignment",
    "AssignmentStatus",
    "AssignmentSubmission",
    "Attempt",
    "Attendance",
    "AttendanceStatus",
    "AuditLog",
    "Base",
    "BlogPost",
    "CategoryKind",
    "Certificate",
    "ClassEnrollment",
    "ClassGroup",
    "ContactLead",
    "ContentCategory",
    "ContentRevision",
    "Course",
    "CourseCategory",
    "CourseEnrollment",
    "DeliveryMode",
    "EnrollmentStatus",
    "FaqItem",
    "LeadNote",
    "LeadStatus",
    "LearningFormat",
    "Lesson",
    "LessonProgress",
    "LiveSession",
    "MediaAsset",
    "MediaKind",
    "Notification",
    "NotificationKind",
    "Order",
    "OrderItem",
    "OrderStatus",
    "ParentProfile",
    "ParentStudentLink",
    "Payment",
    "PaymentStatus",
    "PracticeSession",
    "ProductCategory",
    "Question",
    "QuestionType",
    "QuestionVariant",
    "Resource",
    "ReviewStatus",
    "ScheduleSlot",
    "SessionStatus",
    "SiteSection",
    "SiteSetting",
    "Skill",
    "SkillPrerequisite",
    "SkillRelation",
    "StudentAchievement",
    "StudentProfile",
    "StudentSkillMastery",
    "Subject",
    "Subscription",
    "TeacherCredential",
    "TeacherProfile",
    "TeacherSubjectAssignment",
    "Testimonial",
    "TimestampMixin",
    "Topic",
    "TutoringProduct",
    "TutoringRequest",
    "Unit",
    "User",
    "UserRole",
    "Video",
    "XPEvent",
    "utcnow",
]
