"""admin cms, leads workflow, media, notifications, audit

Revision ID: 20c5518bc200
Revises: a1b2c3d4e5f6
Create Date: 2026-08-13 17:51:16.408640
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text  # noqa: F401 - referenced by autogenerated JSONB(astext_type=Text())
from sqlalchemy.dialects import postgresql

from app.core.text import unique_slug
revision: str = '20c5518bc200'
down_revision: str | None = 'a1b2c3d4e5f6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('tone', sa.String(length=20), nullable=False),
    sa.Column('link_url', sa.String(length=600), nullable=True),
    sa.Column('link_label', sa.String(length=120), nullable=True),
    sa.Column('image_url', sa.String(length=600), nullable=True),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_announcements'))
    )
    op.create_table('content_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=600), nullable=True),
    sa.Column('icon', sa.String(length=60), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_visible_in_nav', sa.Boolean(), nullable=False),
    sa.Column('seo_title', sa.String(length=200), nullable=True),
    sa.Column('seo_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['content_categories.id'], name=op.f('fk_content_categories_parent_id_content_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_categories'))
    )
    with op.batch_alter_table('content_categories', schema=None) as batch_op:
        batch_op.create_index('ix_content_categories_kind_position', ['kind', 'position'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_categories_slug'), ['slug'], unique=True)

    op.create_table('faq_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_faq_items'))
    )
    op.create_table('site_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('group', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site_settings'))
    )
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_settings_key'), ['key'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_email', sa.String(length=320), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.String(length=400), nullable=False),
    sa.Column('changes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_actor_created', ['actor_id', 'created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('content_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_content_revisions_author_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_revisions'))
    )
    with op.batch_alter_table('content_revisions', schema=None) as batch_op:
        batch_op.create_index('ix_content_revisions_entity', ['entity_type', 'entity_id', 'version'], unique=False)

    op.create_table('media_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('original_name', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=800), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('alt_text', sa.String(length=400), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_media_assets_uploaded_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_assets'))
    )
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_assets_checksum'), ['checksum'], unique=False)
        batch_op.create_index('ix_media_assets_kind_created', ['kind', 'created_at'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('audience_role', sa.String(length=20), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link_url', sa.String(length=600), nullable=True),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_audience_role'), ['audience_role'], unique=False)
        batch_op.create_index('ix_notifications_user_read', ['user_id', 'is_read'], unique=False)

    op.create_table('site_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page', sa.String(length=60), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('content', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('published_content', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_site_sections_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site_sections')),
    sa.UniqueConstraint('page', 'key', 'locale', name='page_key_locale')
    )
    with op.batch_alter_table('site_sections', schema=None) as batch_op:
        batch_op.create_index('ix_site_sections_page_position', ['page', 'position'], unique=False)

    op.create_table('teacher_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('organisation', sa.String(length=250), nullable=True),
    sa.Column('year_start', sa.Integer(), nullable=True),
    sa.Column('year_end', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=600), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.id'], name=op.f('fk_teacher_credentials_teacher_id_teacher_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher_credentials'))
    )
    with op.batch_alter_table('teacher_credentials', schema=None) as batch_op:
        batch_op.create_index('ix_teacher_credentials_teacher_kind', ['teacher_id', 'kind'], unique=False)

    op.create_table('course_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['content_categories.id'], name=op.f('fk_course_categories_category_id_content_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_course_categories_course_id_courses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_course_categories')),
    sa.UniqueConstraint('course_id', 'category_id', name='course_category')
    )
    op.create_table('teacher_subject_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('grade', sa.Integer(), nullable=True),
    sa.Column('is_lead', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('fk_teacher_subject_assignments_course_id_courses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_teacher_subject_assignments_subject_id_subjects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.id'], name=op.f('fk_teacher_subject_assignments_teacher_id_teacher_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher_subject_assignments'))
    )
    with op.batch_alter_table('teacher_subject_assignments', schema=None) as batch_op:
        batch_op.create_index('ix_teacher_subject_assignments_teacher', ['teacher_id'], unique=False)

    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['content_categories.id'], name=op.f('fk_product_categories_category_id_content_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['tutoring_products.id'], name=op.f('fk_product_categories_product_id_tutoring_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_categories')),
    sa.UniqueConstraint('product_id', 'category_id', name='product_category')
    )
    op.create_table('lead_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_lead_id', sa.Integer(), nullable=True),
    sa.Column('tutoring_request_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('author_name', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_lead_notes_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_lead_id'], ['contact_leads.id'], name=op.f('fk_lead_notes_contact_lead_id_contact_leads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tutoring_request_id'], ['tutoring_requests.id'], name=op.f('fk_lead_notes_tutoring_request_id_tutoring_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_notes'))
    )
    with op.batch_alter_table('lead_notes', schema=None) as batch_op:
        batch_op.create_index('ix_lead_notes_created', ['created_at'], unique=False)

    with op.batch_alter_table('class_enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=False, server_default='unpaid'))
        batch_op.add_column(sa.Column('preferred_schedule', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('requested_format', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('approved_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('cancelled_reason', sa.Text(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_class_enrollments_approved_by_id_users'), 'users', ['approved_by_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('contact_leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('parent_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('parent_phone', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('school', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('preferred_format', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('preferred_delivery', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('preferred_schedule', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('interested_course_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('interested_product_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assigned_to_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('consultation_result', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('next_follow_up_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('converted_student_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_contact_leads_interested_course_id_courses'), 'courses', ['interested_course_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_contact_leads_converted_student_id_student_profiles'), 'student_profiles', ['converted_student_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_contact_leads_interested_product_id_tutoring_products'), 'tutoring_products', ['interested_product_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_contact_leads_assigned_to_id_users'), 'users', ['assigned_to_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='published'))
        batch_op.add_column(sa.Column('thumbnail_url', sa.String(length=600), nullable=True))
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('seo_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('seo_description', sa.Text(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_courses_teacher_id_teacher_profiles'), 'teacher_profiles', ['teacher_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('draft_blocks', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('has_draft', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('thumbnail_url', sa.String(length=600), nullable=True))
        batch_op.add_column(sa.Column('teacher_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('media_asset_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=False, server_default='0'))
        batch_op.create_foreign_key(batch_op.f('fk_resources_lesson_id_lessons'), 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_resources_media_asset_id_media_assets'), 'media_assets', ['media_asset_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('teacher_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('photo_url', sa.String(length=600), nullable=True))
        batch_op.add_column(sa.Column('teaching_philosophy', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('teaching_style', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('specializations', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('learning_formats', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('video_intro_url', sa.String(length=600), nullable=True))
        batch_op.add_column(sa.Column('gallery', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('social_links', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False, server_default='{}'))
        batch_op.add_column(sa.Column('public_email', sa.String(length=320), nullable=True))
        batch_op.add_column(sa.Column('public_phone', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_teacher_profiles_slug'), ['slug'], unique=True)

    with op.batch_alter_table('tutoring_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_url', sa.String(length=600), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='published'))
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('seo_title', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('seo_description', sa.Text(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_tutoring_products_course_id_courses'), 'courses', ['course_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_tutoring_products_teacher_id_teacher_profiles'), 'teacher_profiles', ['teacher_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('tutoring_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_student_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('parent_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('parent_phone', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('assigned_to_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('consultation_result', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('next_follow_up_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('converted_student_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('source_page', sa.String(length=160), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_tutoring_requests_converted_student_id_student_profiles'), 'student_profiles', ['converted_student_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_tutoring_requests_assigned_to_id_users'), 'users', ['assigned_to_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###

    _backfill()


def _backfill() -> None:
    """Give existing rows sensible values for the columns added above.

    The new columns all have server defaults, so the migration would succeed without this — but
    it would succeed *wrongly*: every existing course would read as a draft-era "published"
    regardless of its ``is_published`` flag, and every existing teacher would silently vanish from
    the public roster the moment the new ``is_published`` filter went live. Demo and production
    data must come through this migration looking exactly as it did before.
    """
    conn = op.get_bind()

    # Courses already carry a published flag; mirror it into the new lifecycle column.
    conn.execute(
        sa.text(
            "UPDATE courses SET status = CASE WHEN is_published THEN 'published' ELSE 'draft' END"
        )
    )

    # Every teacher profile that exists today is already shown on the public site by
    # /tutoring/teachers, which filters only on the user being active. Publishing them preserves
    # that exact behaviour once the new profile pages start filtering on is_published.
    # `true`/`false` keywords rather than 1/0: PostgreSQL will not coerce an integer to boolean
    # here, and SQLite has understood the keywords since 3.23.
    conn.execute(
        sa.text("UPDATE teacher_profiles SET is_published = true WHERE is_published = false")
    )

    # Public teacher URLs need a stable slug. Derive it from the account name, de-duplicating on
    # collision, and fall back to the id so the column is never left empty for an existing row.
    rows = conn.execute(
        sa.text(
            "SELECT tp.id, u.full_name FROM teacher_profiles tp "
            "JOIN users u ON u.id = tp.user_id WHERE tp.slug IS NULL"
        )
    ).all()
    used: set[str] = {
        row[0]
        for row in conn.execute(
            sa.text("SELECT slug FROM teacher_profiles WHERE slug IS NOT NULL")
        ).all()
    }
    for teacher_id, full_name in rows:
        slug = unique_slug(
            full_name,
            lambda candidate: False,
            max_length=150,
            fallback=f"teacher-{teacher_id}",
            reserved=used,
        )
        used.add(slug)
        conn.execute(
            sa.text("UPDATE teacher_profiles SET slug = :slug WHERE id = :id"),
            {"slug": slug, "id": teacher_id},
        )

    # A lesson's draft starts as a copy of its live body, so opening the editor shows the real
    # lesson rather than a blank page.
    conn.execute(sa.text("UPDATE lessons SET draft_blocks = blocks"))
    conn.execute(
        sa.text(
            "UPDATE lessons SET published_at = created_at "
            "WHERE status = 'published' AND published_at IS NULL"
        )
    )

    # Derive each enrollment's payment status from the order that paid for it. Enrollments with
    # no order (free trial places) keep the 'unpaid' default, which is accurate.
    conn.execute(
        sa.text(
            "UPDATE class_enrollments SET payment_status = 'paid' WHERE order_id IN "
            "(SELECT id FROM orders WHERE status = 'paid')"
        )
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutoring_requests', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tutoring_requests_assigned_to_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_tutoring_requests_converted_student_id_student_profiles'), type_='foreignkey')
        batch_op.drop_column('source_page')
        batch_op.drop_column('converted_at')
        batch_op.drop_column('converted_student_id')
        batch_op.drop_column('next_follow_up_at')
        batch_op.drop_column('last_contacted_at')
        batch_op.drop_column('consultation_result')
        batch_op.drop_column('assigned_to_id')
        batch_op.drop_column('parent_phone')
        batch_op.drop_column('parent_name')
        batch_op.drop_column('contact_student_name')

    with op.batch_alter_table('tutoring_products', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tutoring_products_teacher_id_teacher_profiles'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_tutoring_products_course_id_courses'), type_='foreignkey')
        batch_op.drop_column('seo_description')
        batch_op.drop_column('seo_title')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('course_id')
        batch_op.drop_column('teacher_id')
        batch_op.drop_column('status')
        batch_op.drop_column('thumbnail_url')

    with op.batch_alter_table('teacher_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teacher_profiles_slug'))
        batch_op.drop_column('position')
        batch_op.drop_column('is_published')
        batch_op.drop_column('public_phone')
        batch_op.drop_column('public_email')
        batch_op.drop_column('social_links')
        batch_op.drop_column('gallery')
        batch_op.drop_column('video_intro_url')
        batch_op.drop_column('learning_formats')
        batch_op.drop_column('specializations')
        batch_op.drop_column('teaching_style')
        batch_op.drop_column('teaching_philosophy')
        batch_op.drop_column('photo_url')
        batch_op.drop_column('slug')

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_resources_media_asset_id_media_assets'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_resources_lesson_id_lessons'), type_='foreignkey')
        batch_op.drop_column('position')
        batch_op.drop_column('media_asset_id')
        batch_op.drop_column('lesson_id')

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_column('published_at')
        batch_op.drop_column('version')
        batch_op.drop_column('teacher_notes')
        batch_op.drop_column('thumbnail_url')
        batch_op.drop_column('has_draft')
        batch_op.drop_column('draft_blocks')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_courses_teacher_id_teacher_profiles'), type_='foreignkey')
        batch_op.drop_column('seo_description')
        batch_op.drop_column('seo_title')
        batch_op.drop_column('teacher_id')
        batch_op.drop_column('is_featured')
        batch_op.drop_column('thumbnail_url')
        batch_op.drop_column('status')

    with op.batch_alter_table('contact_leads', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_contact_leads_assigned_to_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_contact_leads_interested_product_id_tutoring_products'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_contact_leads_converted_student_id_student_profiles'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_contact_leads_interested_course_id_courses'), type_='foreignkey')
        batch_op.drop_column('converted_at')
        batch_op.drop_column('converted_student_id')
        batch_op.drop_column('next_follow_up_at')
        batch_op.drop_column('last_contacted_at')
        batch_op.drop_column('consultation_result')
        batch_op.drop_column('assigned_to_id')
        batch_op.drop_column('interested_product_id')
        batch_op.drop_column('interested_course_id')
        batch_op.drop_column('preferred_schedule')
        batch_op.drop_column('preferred_delivery')
        batch_op.drop_column('preferred_format')
        batch_op.drop_column('school')
        batch_op.drop_column('parent_phone')
        batch_op.drop_column('parent_name')
        batch_op.drop_column('student_name')

    with op.batch_alter_table('class_enrollments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_class_enrollments_approved_by_id_users'), type_='foreignkey')
        batch_op.drop_column('cancelled_reason')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approved_by_id')
        batch_op.drop_column('requested_format')
        batch_op.drop_column('preferred_schedule')
        batch_op.drop_column('payment_status')

    with op.batch_alter_table('lead_notes', schema=None) as batch_op:
        batch_op.drop_index('ix_lead_notes_created')

    op.drop_table('lead_notes')
    op.drop_table('product_categories')
    with op.batch_alter_table('teacher_subject_assignments', schema=None) as batch_op:
        batch_op.drop_index('ix_teacher_subject_assignments_teacher')

    op.drop_table('teacher_subject_assignments')
    op.drop_table('course_categories')
    with op.batch_alter_table('teacher_credentials', schema=None) as batch_op:
        batch_op.drop_index('ix_teacher_credentials_teacher_kind')

    op.drop_table('teacher_credentials')
    with op.batch_alter_table('site_sections', schema=None) as batch_op:
        batch_op.drop_index('ix_site_sections_page_position')

    op.drop_table('site_sections')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_read')
        batch_op.drop_index(batch_op.f('ix_notifications_audience_role'))

    op.drop_table('notifications')
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.drop_index('ix_media_assets_kind_created')
        batch_op.drop_index(batch_op.f('ix_media_assets_checksum'))

    op.drop_table('media_assets')
    with op.batch_alter_table('content_revisions', schema=None) as batch_op:
        batch_op.drop_index('ix_content_revisions_entity')

    op.drop_table('content_revisions')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_entity')
        batch_op.drop_index('ix_audit_logs_actor_created')

    op.drop_table('audit_logs')
    with op.batch_alter_table('site_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_settings_key'))

    op.drop_table('site_settings')
    op.drop_table('faq_items')
    with op.batch_alter_table('content_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_categories_slug'))
        batch_op.drop_index('ix_content_categories_kind_position')

    op.drop_table('content_categories')
    op.drop_table('announcements')
    # ### end Alembic commands ###
