"""content translations

Revision ID: c75a7d56b2dc
Revises: 20c5518bc200
Create Date: 2026-08-13 20:13:14.229039
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text  # noqa: F401 - used by the autogenerated JSONB variant
from sqlalchemy.dialects import postgresql
revision: str = 'c75a7d56b2dc'
down_revision: str | None = '20c5518bc200'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('i18n', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False, server_default='{}'))

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('i18n', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False, server_default='{}'))

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('i18n', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False, server_default='{}'))

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('i18n', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False, server_default='{}'))

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('i18n', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False, server_default='{}'))

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('i18n', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False, server_default='{}'))

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('i18n', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False, server_default='{}'))

    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('i18n', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False, server_default='{}'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_column('i18n')

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_column('i18n')

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_column('i18n')

    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_column('i18n')

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_column('i18n')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('i18n')

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_column('i18n')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('i18n')

    # ### end Alembic commands ###
